# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vapi - vAPI is an extensible API Platform for modelling and delivering APIs/SDKs/CLIs.


require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::VAPI::VapiStdNestedLocalizableMessage
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VapiStdNestedLocalizableMessage' do
  before do
    # run before each test
    @instance = VSphereAutomation::VAPI::VapiStdNestedLocalizableMessage.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VapiStdNestedLocalizableMessage' do
    it 'should create an instance of VapiStdNestedLocalizableMessage' do
      expect(@instance).to be_instance_of(VSphereAutomation::VAPI::VapiStdNestedLocalizableMessage)
    end
  end
  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "params"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
