=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vapi

# vAPI is an extensible API Platform for modelling and delivering APIs/SDKs/CLIs.


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::VAPI::VapiRestNavigationComponentInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VapiRestNavigationComponentInfo' do
  before do
    # run before each test
    @instance = VSphereAutomation::VAPI::VapiRestNavigationComponentInfo.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VapiRestNavigationComponentInfo' do
    it 'should create an instance of VapiRestNavigationComponentInfo' do
      expect(@instance).to be_instance_of(VSphereAutomation::VAPI::VapiRestNavigationComponentInfo)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "services"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "documentation"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
