# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# stats - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::VStats::VstatsEndpointsFilterSpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VstatsEndpointsFilterSpec' do
  before do
    # run before each test
    @instance = VSphereAutomation::VStats::VstatsEndpointsFilterSpec.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VstatsEndpointsFilterSpec' do
    it 'should create an instance of VstatsEndpointsFilterSpec' do
      expect(@instance).to be_instance_of(VSphereAutomation::VStats::VstatsEndpointsFilterSpec)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "push_data_format"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
