# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# stats - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::VStats::VstatsAcqSpecsStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VstatsAcqSpecsStatus' do
  before do
    # run before each test
    @instance = VSphereAutomation::VStats::VstatsAcqSpecsStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VstatsAcqSpecsStatus' do
    it 'should create an instance of VstatsAcqSpecsStatus' do
      expect(@instance).to be_instance_of(VSphereAutomation::VStats::VstatsAcqSpecsStatus)
    end
  end
end
