# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# esx - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::ESX::HealthHostsPerspectivesPlannedMaintenanceStatusApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HealthHostsPerspectivesPlannedMaintenanceStatusApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::ESX::HealthHostsPerspectivesPlannedMaintenanceStatusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HealthHostsPerspectivesPlannedMaintenanceStatusApi' do
    it 'should create an instance of HealthHostsPerspectivesPlannedMaintenanceStatusApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::ESX::HealthHostsPerspectivesPlannedMaintenanceStatusApi)
    end
  end

  # unit tests for check
  # Check if the given host can safely enter maintenance mode.
  # @param host Contains the MoID identifying the ESXi host.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :request_body 
  # @return [EsxHealthStatusInfo]
  describe 'check test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
