# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# esx - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::ESX::SettingsDepotsOfflineApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsDepotsOfflineApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::ESX::SettingsDepotsOfflineApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsDepotsOfflineApi' do
    it 'should create an instance of SettingsDepotsOfflineApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::ESX::SettingsDepotsOfflineApi)
    end
  end

  # unit tests for create_task
  # Imports a new offline software depot. This will also import the metadata and payloads from this offline depot. The returned task will fail and no Offline Depot would be created if there are any issues during import. The result of this operation can be queried by calling the cis/tasks/{task-id} where the task-id is the response of this operation.
  # @param [Hash] opts the optional parameters
  # @option opts [EsxSettingsDepotsOfflineCreateSpec] :request_body 
  # @return [String]
  describe 'create_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Removes a depot from the list of imported offline software depots.
  # @param depot Identifier of the depot to be removed.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Gets the information about an imported offline software depot.
  # @param depot Identifier for the depot.
  # @param [Hash] opts the optional parameters
  # @return [EsxSettingsDepotsOfflineInfo]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # Returns currently imported offline software depots.
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, EsxSettingsDepotsOfflineSummary>]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
