# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# esx - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::ESX::SettingsClustersSoftwareApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsClustersSoftwareApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::ESX::SettingsClustersSoftwareApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsClustersSoftwareApi' do
    it 'should create an instance of SettingsClustersSoftwareApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::ESX::SettingsClustersSoftwareApi)
    end
  end

  # unit tests for apply_task
  # Applies the desired software document associated with the given cluster to hosts within the cluster. If {@basename ApplySpec#commit} {@term field} is {@term set}, it implies the minimum commit that the {@link esx.settings.clusters.Software#apply} {@term operation} should use, however if subsequent commits have been made to the desired state document the apply {@term operation} will use the most recent desired state document. The result of this operation can be queried by calling the cis/tasks/{task-id} where the task-id is the response of this operation.
  # @param cluster Identifier of the cluster.
  # @param [Hash] opts the optional parameters
  # @option opts [EsxSettingsClustersSoftwareApplySpec] :request_body 
  # @return [String]
  describe 'apply_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for check_task
  # Runs checks on the cluster before applying the desired software document across all hosts in the cluster. Checks if all hosts in the cluster are in a good state to be updated with the desired software document. If {@basename CheckSpec#commit} {@term field} is {@term set} it implies the minimum commit that the check {@term operation} should use, however if subsequent commits have been made to the desired state document the check {@term operation} will use the most recent desired state document. The result of this operation can be queried by calling the cis/tasks/{task-id} where the task-id is the response of this operation.
  # @param cluster Identifier of the cluster.
  # @param [Hash] opts the optional parameters
  # @option opts [EsxSettingsClustersSoftwareCheckSpec] :request_body 
  # @return [String]
  describe 'check_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for export
  # Exports the desired software specification document and/or image. This API will not export the solution section of the desired software specification.
  # @param cluster Identifier of the cluster.
  # @param [Hash] opts the optional parameters
  # @option opts [EsxSettingsClustersSoftwareExportSpec] :request_body 
  # @return [Hash<String, String>]
  describe 'export test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Returns the complete desired software specification.
  # @param cluster Identifier of the cluster.
  # @param [Hash] opts the optional parameters
  # @return [EsxSettingsSoftwareInfo]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scan_task
  # Scans all the hosts in the cluster against the cluster&#39;s desired state. The result of this operation can be queried by calling the cis/tasks/{task-id} where the task-id is the response of this operation.
  # @param cluster Identifier of the cluster.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'scan_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
