# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# esx - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::ESX::SettingsInternalSummaryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsInternalSummaryApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::ESX::SettingsInternalSummaryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsInternalSummaryApi' do
    it 'should create an instance of SettingsInternalSummaryApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::ESX::SettingsInternalSummaryApi)
    end
  end

  # unit tests for get
  # Summarize the compliance result of the clusters. The API will return the cluster summary with an empty compliance result and/or desired software specification if the service failed get this information from the database due to unexpected scenarios.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :folder Identifier of the folder entity. Exactly one of {@name #folder} or {@name #datacenter} must be specified.
  # @option opts [String] :datacenter Identifier of the datacenter entity Exactly one of {@name #folder} or {@name #datacenter} must be specified.
  # @return [Hash<String, EsxSettingsInternalSummaryClusterSummary>]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scan_task
  # Scans all the clusters to get their compliance information against its respective desired state.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :folder Identifier of the folder entity. Exactly one of {@name #folder} or {@name #datacenter} must be specified.
  # @option opts [String] :datacenter Identifier of the datacenter entity Exactly one of {@name #folder} or {@name #datacenter} must be specified.
  # @return [String]
  describe 'scan_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
