# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# esx - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::ESX::SettingsClustersSoftwareSolutionsNsxNsxInternalApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsClustersSoftwareSolutionsNsxNsxInternalApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::ESX::SettingsClustersSoftwareSolutionsNsxNsxInternalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsClustersSoftwareSolutionsNsxNsxInternalApi' do
    it 'should create an instance of SettingsClustersSoftwareSolutionsNsxNsxInternalApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::ESX::SettingsClustersSoftwareSolutionsNsxNsxInternalApi)
    end
  end

  # unit tests for apply_task
  # Applies the NSX Component specified in the desired specification document to the hosts in the cluster. Warning: This operation is part of a new feature in development. It may be changed at any time and may not have all supported functionality implemented.
  # @param cluster Identifier of the cluster.
  # @param [Hash] opts the optional parameters
  # @option opts [EsxSettingsClustersSoftwareSolutionsNsxNsxInternalApplySpec] :request_body 
  # @return [String]
  describe 'apply_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
