# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# esx - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::ESX::SettingsClustersSoftwareReportsApplyImpactApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsClustersSoftwareReportsApplyImpactApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::ESX::SettingsClustersSoftwareReportsApplyImpactApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsClustersSoftwareReportsApplyImpactApi' do
    it 'should create an instance of SettingsClustersSoftwareReportsApplyImpactApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::ESX::SettingsClustersSoftwareReportsApplyImpactApi)
    end
  end

  # unit tests for get
  # Returns a summary of how hosts within the cluster will be impacted during an apply {@term operation}. The impact is generated from the compliance information obtained from {@link esx.settings.clusters.software.Compliance#get}
  # @param cluster The cluster identifier.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :hosts The specific hosts for which an impact is to be generated.
  # @return [EsxSettingsClustersSoftwareReportsApplyImpactClusterImpact]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
