# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# esx - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::ESX::SettingsHostsSoftwareDraftsSoftwareHardwareSupportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsHostsSoftwareDraftsSoftwareHardwareSupportApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::ESX::SettingsHostsSoftwareDraftsSoftwareHardwareSupportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsHostsSoftwareDraftsSoftwareHardwareSupportApi' do
    it 'should create an instance of SettingsHostsSoftwareDraftsSoftwareHardwareSupportApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::ESX::SettingsHostsSoftwareDraftsSoftwareHardwareSupportApi)
    end
  end

  # unit tests for delete
  # Deletes a given host&#39;s working copy document Hardware Support Package configuration.
  # @param host Identifier for the host.
  # @param draft Identifier of image working copy document being updated
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Returns a given host&#39;s working copy document Hardware Support Package (HSP) configuration.
  # @param host Identifier for the host.
  # @param draft Identifier of image working copy document being updated
  # @param [Hash] opts the optional parameters
  # @return [EsxSettingsHardwareSupportInfo]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set
  # Replaces a given host&#39;s working copy document Hardware Support Package (HSP) configured.
  # @param host Identifier for the host.
  # @param draft Identifier of image working copy document being updated
  # @param [Hash] opts the optional parameters
  # @option opts [EsxSettingsHardwareSupportSpec] :request_body 
  # @return [nil]
  describe 'set test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
