# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# esx - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::ESX::EsxSettingsDefaultsClustersPoliciesApplySet
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EsxSettingsDefaultsClustersPoliciesApplySet' do
  before do
    # run before each test
    @instance = VSphereAutomation::ESX::EsxSettingsDefaultsClustersPoliciesApplySet.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EsxSettingsDefaultsClustersPoliciesApplySet' do
    it 'should create an instance of EsxSettingsDefaultsClustersPoliciesApplySet' do
      expect(@instance).to be_instance_of(VSphereAutomation::ESX::EsxSettingsDefaultsClustersPoliciesApplySet)
    end
  end
end
