# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# esx - No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::ESX::EsxSettingsClustersSoftwareDraftsCommitSpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EsxSettingsClustersSoftwareDraftsCommitSpec' do
  before do
    # run before each test
    @instance = VSphereAutomation::ESX::EsxSettingsClustersSoftwareDraftsCommitSpec.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EsxSettingsClustersSoftwareDraftsCommitSpec' do
    it 'should create an instance of EsxSettingsClustersSoftwareDraftsCommitSpec' do
      expect(@instance).to be_instance_of(VSphereAutomation::ESX::EsxSettingsClustersSoftwareDraftsCommitSpec)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
