=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# appliance

# The vCenter Server Appliance is a preconfigured Linux-based virtual machine optimized for running vCenter Server and associated services.


=end

require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::Appliance::LocalAccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LocalAccountsApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::Appliance::LocalAccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LocalAccountsApi' do
    it 'should create an instance of LocalAccountsApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::Appliance::LocalAccountsApi)
    end
  end

  # unit tests for create
  # Create a new local user account.
  # @param username User login name
  # @param appliance_local_accounts_create 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Delete a local user account.
  # @param username User login name
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Get the local user account information.
  # @param username User login name
  # @param [Hash] opts the optional parameters
  # @return [ApplianceLocalAccountsResult]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # Get a list of the local user accounts.
  # @param [Hash] opts the optional parameters
  # @return [ApplianceLocalAccountsListResult]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set
  # Set local user account properties.
  # @param username User login name
  # @param appliance_local_accounts_set 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'set test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Update selected fields in local user account properties.
  # @param username User login name
  # @param appliance_local_accounts_update 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
