=begin
#appliance

#The vCenter Server Appliance is a preconfigured Linux-based virtual machine optimized for running vCenter Server and associated services.

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::Appliance::LoggingForwardingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LoggingForwardingApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::Appliance::LoggingForwardingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoggingForwardingApi' do
    it 'should create an instance of LoggingForwardingApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::Appliance::LoggingForwardingApi)
    end
  end

  # unit tests for get
  # Returns the configuration for forwarding log messages to remote logging servers.
  # @param [Hash] opts the optional parameters
  # @return [ApplianceLoggingForwardingResult]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set
  # Sets the configuration for forwarding log messages to remote log servers.
  # @param [Hash] opts the optional parameters
  # @option opts [ApplianceLoggingForwardingSet] :appliance_logging_forwarding_set 
  # @return [nil]
  describe 'set test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for test
  # Validates the current log forwarding configuration by checking the liveness of the remote machine and optionally sending a test diagnostic log message from the appliance to all configured logging servers to allow manual end-to-end validation. The message that is sent is: \&quot;This is a diagnostic log test message from vCenter Server.\&quot;
  # @param appliance_logging_forwarding_test 
  # @param [Hash] opts the optional parameters
  # @return [ApplianceLoggingForwardingTestResult]
  describe 'test test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
