=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# appliance

# The vCenter Server Appliance is a preconfigured Linux-based virtual machine optimized for running vCenter Server and associated services.


=end

require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::Appliance::NetworkingInterfacesIpv6Api
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NetworkingInterfacesIpv6Api' do
  before do
    # run before each test
    @instance = VSphereAutomation::Appliance::NetworkingInterfacesIpv6Api.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NetworkingInterfacesIpv6Api' do
    it 'should create an instance of NetworkingInterfacesIpv6Api' do
      expect(@instance).to be_instance_of(VSphereAutomation::Appliance::NetworkingInterfacesIpv6Api)
    end
  end

  # unit tests for get
  # Get IPv6 network configuration for specific interface.
  # @param interface_name Network interface to query, for example, \&quot;nic0\&quot;.
  # @param [Hash] opts the optional parameters
  # @return [ApplianceNetworkingInterfacesIpv6Result]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set
  # Set IPv6 network configuration for specific interface.
  # @param interface_name Network interface to update, for example, \&quot;nic0\&quot;.
  # @param appliance_networking_interfaces_ipv6_set 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'set test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
