# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# appliance - The vCenter Server Appliance is a preconfigured Linux-based virtual machine optimized for running vCenter Server and associated services.


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::Appliance::ObservabilityInternalSettingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ObservabilityInternalSettingsApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::Appliance::ObservabilityInternalSettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ObservabilityInternalSettingsApi' do
    it 'should create an instance of ObservabilityInternalSettingsApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::Appliance::ObservabilityInternalSettingsApi)
    end
  end

  # unit tests for get
  # Gets values for the particular key from observability settings. if you do not have all of the privileges described as follows:     -  Operation execution requires Observability.Admin.  
  # @param key Observability setting key for which value to be retrieved.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_keys
  # Gets keys of all the existing observability settings. if you do not have all of the privileges described as follows:     -  Operation execution requires Observability.Admin.  
  # @param [Hash] opts the optional parameters
  # @return [Array<String>]
  describe 'get_keys test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_settings
  # Gets all existing observability settings. if you do not have all of the privileges described as follows:     -  Operation execution requires Observability.Admin.  
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_settings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Updates observability settings. if you do not have all of the privileges described as follows:     -  Operation execution requires Observability.Admin.  
  # @param key Key of Setting to be updated.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :request_body 
  # @return [nil]
  describe 'update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
