=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# appliance

# The vCenter Server Appliance is a preconfigured Linux-based virtual machine optimized for running vCenter Server and associated services.


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::Appliance::ApplianceTechpreviewMonitoringSnmpSNMPHashConfig
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ApplianceTechpreviewMonitoringSnmpSNMPHashConfig' do
  before do
    # run before each test
    @instance = VSphereAutomation::Appliance::ApplianceTechpreviewMonitoringSnmpSNMPHashConfig.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplianceTechpreviewMonitoringSnmpSNMPHashConfig' do
    it 'should create an instance of ApplianceTechpreviewMonitoringSnmpSNMPHashConfig' do
      expect(@instance).to be_instance_of(VSphereAutomation::Appliance::ApplianceTechpreviewMonitoringSnmpSNMPHashConfig)
    end
  end
  describe 'test attribute "auth_hash"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "priv_hash"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "raw_secret"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
