=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# cis

# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::CIS::CisTaggingCategoryUpdateSpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CisTaggingCategoryUpdateSpec' do
  before do
    # run before each test
    @instance = VSphereAutomation::CIS::CisTaggingCategoryUpdateSpec.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CisTaggingCategoryUpdateSpec' do
    it 'should create an instance of CisTaggingCategoryUpdateSpec' do
      expect(@instance).to be_instance_of(VSphereAutomation::CIS::CisTaggingCategoryUpdateSpec)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "cardinality"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "associable_types"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
