=begin
#cis

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::CIS::CisTasksGetSpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CisTasksGetSpec' do
  before do
    # run before each test
    @instance = VSphereAutomation::CIS::CisTasksGetSpec.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CisTasksGetSpec' do
    it 'should create an instance of CisTasksGetSpec' do
      expect(@instance).to be_instance_of(VSphereAutomation::CIS::CisTasksGetSpec)
    end
  end
  describe 'test attribute "return_all"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "exclude_result"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
