=begin
#cis

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::CIS::CisTaggingTagAssociationDetach
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CisTaggingTagAssociationDetach' do
  before do
    # run before each test
    @instance = VSphereAutomation::CIS::CisTaggingTagAssociationDetach.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CisTaggingTagAssociationDetach' do
    it 'should create an instance of CisTaggingTagAssociationDetach' do
      expect(@instance).to be_instance_of(VSphereAutomation::CIS::CisTaggingTagAssociationDetach)
    end
  end
  describe 'test attribute "object_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
