=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# cis

# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::CIS::VapiStdErrorsUnauthenticated
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VapiStdErrorsUnauthenticated' do
  before do
    # run before each test
    @instance = VSphereAutomation::CIS::VapiStdErrorsUnauthenticated.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VapiStdErrorsUnauthenticated' do
    it 'should create an instance of VapiStdErrorsUnauthenticated' do
      expect(@instance).to be_instance_of(VSphereAutomation::CIS::VapiStdErrorsUnauthenticated)
    end
  end
  describe 'test attribute "messages"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
