=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# cis

# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)


=end

module VSphereAutomation
  module CIS
    VERSION = '0.1.0'
  end
end
