# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter - VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::VCenter::ClusterModulesVmMembersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ClusterModulesVmMembersApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::ClusterModulesVmMembersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClusterModulesVmMembersApi' do
    it 'should create an instance of ClusterModulesVmMembersApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::ClusterModulesVmMembersApi)
    end
  end

  # unit tests for add
  # Adds virtual machines to the module. These virtual machines are required to be in the same vCenter cluster. Warning: This operation is part of a new feature in development. It may be changed at any time and may not have all supported functionality implemented.
  # @param _module Identifier of the module to which the specified virtual machines are added. The parameter must be an identifier for the resource type: vcenter.cluster.modules.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [VcenterClusterModulesVmMembersAddResp]
  describe 'add test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get
  # Returns the virtual machines that are members of the module. Warning: This operation is part of a new feature in development. It may be changed at any time and may not have all supported functionality implemented.
  # @param _module Identifier of the module to be queried for its virtual machines. The parameter must be an identifier for the resource type: vcenter.cluster.modules.
  # @param [Hash] opts the optional parameters
  # @return [VcenterClusterModulesVmMembersResp]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove
  # Removes virtual machines from the module. Warning: This operation is part of a new feature in development. It may be changed at any time and may not have all supported functionality implemented.
  # @param _module Identifier of the module from which the specified virtual machines are removed. The parameter must be an identifier for the resource type: vcenter.cluster.modules.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [VcenterClusterModulesVmMembersRemoveResp]
  describe 'remove test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
