# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter - VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::VCenter::ClusterEdrsAlgoParameterApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ClusterEdrsAlgoParameterApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::ClusterEdrsAlgoParameterApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClusterEdrsAlgoParameterApi' do
    it 'should create an instance of ClusterEdrsAlgoParameterApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::ClusterEdrsAlgoParameterApi)
    end
  end

  # unit tests for get
  # Gets EDRS algorithm parameters for a given cluster. Warning: This operation is available as Technology Preview. These are early access APIs provided to test, automate and provide feedback on the feature. Since this can change based on feedback, VMware does not guarantee backwards compatibility and recommends against using them in production environments. Some Technology Preview APIs might only be applicable to specific environments. if you do not have all of the privileges described as follows:     -  The resource ClusterComputeResource referenced by the parameter cluster requires System.Read.  
  # @param cluster Identifier of cluster whose EDRS algorithm parameters need to be returned. The parameter must be an identifier for the resource type: ClusterComputeResource.
  # @param [Hash] opts the optional parameters
  # @return [VcenterClusterEdrsAlgoParameterResp]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set
  # Sets EDRS algorithm parameters for a given cluster. Warning: This operation is available as Technology Preview. These are early access APIs provided to test, automate and provide feedback on the feature. Since this can change based on feedback, VMware does not guarantee backwards compatibility and recommends against using them in production environments. Some Technology Preview APIs might only be applicable to specific environments. if you do not have all of the privileges described as follows:     -  The resource ClusterComputeResource referenced by the parameter cluster requires Host.Inventory.EditCluster.  
  # @param cluster Identifier of cluster whose EDRS need to be configured. The parameter must be an identifier for the resource type: ClusterComputeResource.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'set test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
