=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter

# VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


=end

require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::VCenter::GuestCustomizationSpecsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GuestCustomizationSpecsApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::GuestCustomizationSpecsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GuestCustomizationSpecsApi' do
    it 'should create an instance of GuestCustomizationSpecsApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::GuestCustomizationSpecsApi)
    end
  end

  # unit tests for list
  # Returns information about at most 1000 visible (subject to permission checks) guest customization specifications in vCenter matching the CustomizationSpecs.FilterSpec.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :filter_names Names that guest customization specifications must have to match the filter (see CustomizationSpecs.Summary.name). If unset or empty, guest customization specifications with any name match the filter. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vcenter.guest.CustomizationSpec. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vcenter.guest.CustomizationSpec.
  # @option opts [String] :filter_os_type The CustomizationSpecs.OsType enumerated type defines the types of guest operating systems for which guest customization is supported.
  # @return [VcenterGuestCustomizationSpecsListResult]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
