# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter - VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::VCenter::LcmUpdatePrecheckReportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LcmUpdatePrecheckReportApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::LcmUpdatePrecheckReportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LcmUpdatePrecheckReportApi' do
    it 'should create an instance of LcmUpdatePrecheckReportApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::LcmUpdatePrecheckReportApi)
    end
  end

  # unit tests for create_task
  # Creates a vCenter Server pre-update compatibility check report for the pending update version. The report can be exported and downloaded in CSV format.   The result of this operation can be queried by calling the cis.Tasks#get operation where task is the response of this operation. 
  # @param version Pending update version for which pre-update compatibility check will be executed. The parameter must be an identifier for the resource type: vcenter.lcm.update.pending.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'create_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
