# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter - VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::VCenter::SettingsNamespacesItemsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SettingsNamespacesItemsApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::SettingsNamespacesItemsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SettingsNamespacesItemsApi' do
    it 'should create an instance of SettingsNamespacesItemsApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::SettingsNamespacesItemsApi)
    end
  end

  # unit tests for list
  # Returns a map of  item values corresponding to the keys in the namespace. The readPrivilege defined in the namespace is checked before the operation is initiated. If keys is not passed in, the entire map of KV pairs are returned. Usage beyond VMware Cloud on AWS is not supported. Warning: This operation is part of a new feature in development. It may be changed at any time and may not have all supported functionality implemented.
  # @param namespace the targetted namespace
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :keys 
  # @return [VcenterSettingsNamespacesItemsListResp]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put
  # Put a map of key value pairs in the namespace. This overrides any existing key/value if they already exist in the namespace. The writePrivilege defined in the namespace is checked before the operation is initiated. When the value is not passed in the map items, the item in the namespace is deleted. When an empty (0 length) String, \&quot;\&quot;, is passed in as the value, the value is set to \&quot;\&quot;. Usage beyond VMware Cloud on AWS is not supported. Warning: This operation is part of a new feature in development. It may be changed at any time and may not have all supported functionality implemented.
  # @param namespace the targetted namespace
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
