# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter - VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::VCenter::StatsTopnHostByClusterApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatsTopnHostByClusterApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::StatsTopnHostByClusterApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatsTopnHostByClusterApi' do
    it 'should create an instance of StatsTopnHostByClusterApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::StatsTopnHostByClusterApi)
    end
  end

  # unit tests for get
  # Retrieve Top N hosts in a cluster. Warning: This operation is part of a new feature in development. It may be changed at any time and may not have all supported functionality implemented.
  # @param counter name of the performance counter which could be CPU Usage (MHz PERCENT), Memory usage [consumed], Disk usage (KBPS), Network usage (MBPS) etc.
  # @param top indicates how many top values to return.
  # @param cluster cluster that hosts should belong to.
  # @param interval desired roll-up duration in seconds.
  # @param start StartTime of the time window for topN query.
  # @param [Hash] opts the optional parameters
  # @option opts [DateTime] :_end 
  # @option opts [String] :verbosity 
  # @return [VcenterStatsTopnHostByClusterResp]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
