# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter - VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::VCenter::TrustedInfrastructureTrustAuthorityClustersAttestationOsEsxBaseImagesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TrustedInfrastructureTrustAuthorityClustersAttestationOsEsxBaseImagesApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::TrustedInfrastructureTrustAuthorityClustersAttestationOsEsxBaseImagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TrustedInfrastructureTrustAuthorityClustersAttestationOsEsxBaseImagesApi' do
    it 'should create an instance of TrustedInfrastructureTrustAuthorityClustersAttestationOsEsxBaseImagesApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::TrustedInfrastructureTrustAuthorityClustersAttestationOsEsxBaseImagesApi)
    end
  end

  # unit tests for delete_task
  # Remove a trusted ESX base image of each ESX in the cluster.
  # @param cluster The id of the cluster on which the operation will be executed. The parameter must be an identifier for the resource type: ClusterComputeResource.
  # @param version The ESX base image version. The parameter must be an identifier for the resource type: vcenter.trusted_infrastructure.trust_authority_clusters.attestation.os.esx.BaseImage.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'delete_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_task
  # Get the trusted ESX base version details.
  # @param cluster The id of the cluster on which the operation will be executed. The parameter must be an identifier for the resource type: ClusterComputeResource.
  # @param version The ESX base image version. The parameter must be an identifier for the resource type: vcenter.trusted_infrastructure.trust_authority_clusters.attestation.os.esx.BaseImage.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'get_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for import_from_imgdb_task
  # Import ESX metadata as a new trusted base image to each host in the cluster.   Import a boot_imgdb.tgz file which contains metadata that describes a trusted ESX base image. A boot_imgdb.tgz file can be downloaded from a representative host. 
  # @param cluster The id of the cluster on which the operation will be executed. The parameter must be an identifier for the resource type: ClusterComputeResource.
  # @param [Hash] opts the optional parameters
  # @option opts [File] :request_body 
  # @return [String]
  describe 'import_from_imgdb_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_task
  # Return a list of trusted ESX base images.
  # @param cluster The id of the cluster on which the operation will be executed. The parameter must be an identifier for the resource type: ClusterComputeResource.
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :version Search criteria by ESX base image version numbers. version if {@term.unset} return all ESX version numbers. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vcenter.trusted_infrastructure.trust_authority_clusters.attestation.os.esx.BaseImage. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vcenter.trusted_infrastructure.trust_authority_clusters.attestation.os.esx.BaseImage.
  # @option opts [Array<String>] :display_name Search criteria by ESX base image version version numbers. displayName if {@term.unset} return all ESX display version numbers.
  # @option opts [Array<String>] :health Search criteria by health indicator. health if {@term.unset} return all health indicators.
  # @return [String]
  describe 'list_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
