# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter - VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::VCenter::VmGuestEnvironmentApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VmGuestEnvironmentApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::VmGuestEnvironmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VmGuestEnvironmentApi' do
    it 'should create an instance of VmGuestEnvironmentApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::VmGuestEnvironmentApi)
    end
  end

  # unit tests for get
  # Reads a single environment variable from the guest operating system.   If the authentication uses Credentials.interactive-session, then the environment being read will be that of the user logged into the desktop. Otherwise it&#39;s the environment of the system user.    . Warning: This operation is part of a new feature in development. It may be changed at any time and may not have all supported functionality implemented.
  # @param vm Virtual machine to perform the operation on. The parameter must be an identifier for the resource type: VirtualMachine.
  # @param name The name of the environment variable to be read.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [VcenterVmGuestEnvironmentResp]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # Reads a list of environment variables from the guest operating system.   If the authentication uses Credentials.interactive-session, then the environment being read will be that of the user logged into the desktop. Otherwise it&#39;s the environment of the system user.    . Warning: This operation is part of a new feature in development. It may be changed at any time and may not have all supported functionality implemented.
  # @param vm Virtual machine to perform the operation on. The parameter must be an identifier for the resource type: VirtualMachine.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [VcenterVmGuestEnvironmentListResp]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
