=begin
#vcenter

#VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::VCenter::VmStoragePolicyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VmStoragePolicyApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::VmStoragePolicyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VmStoragePolicyApi' do
    it 'should create an instance of VmStoragePolicyApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::VmStoragePolicyApi)
    end
  end

  # unit tests for get
  # Returns Information about Storage Policy associated with a virtual machine&#39;s home directory and/or its virtual hard disks.
  # @param vm Virtual machine identifier The parameter must be an identifier for the resource type: VirtualMachine.
  # @param [Hash] opts the optional parameters
  # @return [VcenterVmStoragePolicyResult]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Updates the storage policy configuration of a virtual machine and/or its associated virtual hard disks.
  # @param vm Virtual machine identifier. The parameter must be an identifier for the resource type: VirtualMachine.
  # @param [Hash] opts the optional parameters
  # @option opts [VcenterVmStoragePolicyUpdate] :vcenter_vm_storage_policy_update 
  # @return [nil]
  describe 'update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
