source 'https://rubygems.org'

gemspec
gem 'pry'
gem 'vsphere-automation-appliance', path: '../appliance'
gem 'vsphere-automation-cis', path: '../cis'
gem 'vsphere-automation-content', path: '../content'
gem 'vsphere-automation-vapi', path: '../vapi'
gem 'vsphere-automation-vcenter', path: '../vcenter'

group :development, :test do
  gem 'rake', '~> 12.0.0'
end
