=begin
#content

#VMware vSphere® Content Library empowers vSphere Admins to effectively manage VM templates, vApps, ISO images and scripts with ease.

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::Content::ContentLibraryItemDownloadSessionKeepAlive
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContentLibraryItemDownloadSessionKeepAlive' do
  before do
    # run before each test
    @instance = VSphereAutomation::Content::ContentLibraryItemDownloadSessionKeepAlive.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContentLibraryItemDownloadSessionKeepAlive' do
    it 'should create an instance of ContentLibraryItemDownloadSessionKeepAlive' do
      expect(@instance).to be_instance_of(VSphereAutomation::Content::ContentLibraryItemDownloadSessionKeepAlive)
    end
  end
  describe 'test attribute "progress"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
