=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# content

# VMware vSphere® Content Library empowers vSphere Admins to effectively manage VM templates, vApps, ISO images and scripts with ease.


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::Content::ContentSubscribedLibraryProbe
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContentSubscribedLibraryProbe' do
  before do
    # run before each test
    @instance = VSphereAutomation::Content::ContentSubscribedLibraryProbe.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContentSubscribedLibraryProbe' do
    it 'should create an instance of ContentSubscribedLibraryProbe' do
      expect(@instance).to be_instance_of(VSphereAutomation::Content::ContentSubscribedLibraryProbe)
    end
  end
  describe 'test attribute "subscription_info"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
