=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter

# VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::VCenter::VcenterVchaClusterWitnessRedeploySpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VcenterVchaClusterWitnessRedeploySpec' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::VcenterVchaClusterWitnessRedeploySpec.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VcenterVchaClusterWitnessRedeploySpec' do
    it 'should create an instance of VcenterVchaClusterWitnessRedeploySpec' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::VcenterVchaClusterWitnessRedeploySpec)
    end
  end
  describe 'test attribute "vc_spec"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "placement"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ha_ip"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
