=begin
# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter

# VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::VCenter::VcenterVmHardwareMemoryInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VcenterVmHardwareMemoryInfo' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::VcenterVmHardwareMemoryInfo.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VcenterVmHardwareMemoryInfo' do
    it 'should create an instance of VcenterVmHardwareMemoryInfo' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::VcenterVmHardwareMemoryInfo)
    end
  end
  describe 'test attribute "size_mi_b"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "hot_add_enabled"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "hot_add_increment_size_mi_b"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "hot_add_limit_mi_b"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
