# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# vcenter - VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments


require 'spec_helper'
require 'json'
require 'date'

# Unit tests for VSphereAutomation::VCenter::VcenterVmGuestFilesystemTransfersFileAttributesCreateSpec
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VcenterVmGuestFilesystemTransfersFileAttributesCreateSpec' do
  before do
    # run before each test
    @instance = VSphereAutomation::VCenter::VcenterVmGuestFilesystemTransfersFileAttributesCreateSpec.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VcenterVmGuestFilesystemTransfersFileAttributesCreateSpec' do
    it 'should create an instance of VcenterVmGuestFilesystemTransfersFileAttributesCreateSpec' do
      expect(@instance).to be_instance_of(VSphereAutomation::VCenter::VcenterVmGuestFilesystemTransfersFileAttributesCreateSpec)
    end
  end
  describe 'test attribute "last_accessed"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "last_modified"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "posix"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "windows"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
