# Copyright (c) 2018-2019 VMware, Inc.  All Rights Reserved.
# SPDX-License-Identifier: MIT

# DO NOT MODIFY. THIS CODE IS GENERATED. CHANGES WILL BE OVERWRITTEN.

# content - VMware vSphere® Content Library empowers vSphere Admins to effectively manage VM templates, vApps, ISO images and scripts with ease.


require 'spec_helper'
require 'json'

# Unit tests for VSphereAutomation::Content::LibraryItemChangesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LibraryItemChangesApi' do
  before do
    # run before each test
    @instance = VSphereAutomation::Content::LibraryItemChangesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LibraryItemChangesApi' do
    it 'should create an instance of LibraryItemChangesApi' do
      expect(@instance).to be_instance_of(VSphereAutomation::Content::LibraryItemChangesApi)
    end
  end

  # unit tests for get
  # Returns information about a library item change.
  # @param library_item Library item identifer.
  # @param version Library item version.
  # @param [Hash] opts the optional parameters
  # @return [ContentLibraryItemChangesResp]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # Returns commonly used information about the content changes made to a library item.
  # @param library_item Library item identifier.
  # @param [Hash] opts the optional parameters
  # @return [ContentLibraryItemChangesListResp]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
